services:
  backend:
    build: ./backend
    container_name: portafolio-backend

    env_file:
      - ./backend/.env

    restart: unless-stopped

    networks:
      - portafolio
      - proxy

    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: portafolio-frontend

    depends_on:
      - backend

    restart: unless-stopped

    networks:
      - portafolio
      - proxy

    ports:
      - "5173:80"

networks:
  portafolio:
    driver: bridge
  proxy:
    external: true
